name: Check Markdown links
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

    # We always succeed because some links block us as a scraper.
    - name: Force job success
      if: ${{ always() }}
